//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDF.Data {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDF.Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 实体数据库上下文对象 &quot;{0}&quot; 中不存在定义了实体类型 &quot;{1}&quot; 的 Db&lt;TEntity&gt; 属性。 的本地化字符串。
        /// </summary>
        public static string DbContextEntityTypeCheckErrorMessage {
            get {
                return ResourceManager.GetString("DbContextEntityTypeCheckErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前工厂类型没有定义 DbProviderAttribute 属性。 的本地化字符串。
        /// </summary>
        public static string NotDefinedDbProviderAttribute {
            get {
                return ResourceManager.GetString("NotDefinedDbProviderAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前应用程序运行环境中不存在标记了 DbProviderAttribute 特性 ProviderName 属性为 &quot;{0}&quot; 的 DatabaseFactory 子类。 的本地化字符串。
        /// </summary>
        public static string NotExistsAllowedDbProviderAttributeDatabaseFactory {
            get {
                return ResourceManager.GetString("NotExistsAllowedDbProviderAttributeDatabaseFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到标记了 DbProviderAttribute 为 &quot;{0}&quot; 的 DbScriptParameterParser 子类。 的本地化字符串。
        /// </summary>
        public static string NotExistsAllowedDbProviderAttributeDbScriptParameterParser {
            get {
                return ResourceManager.GetString("NotExistsAllowedDbProviderAttributeDbScriptParameterParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前应用程序配置文件中不存在任何数据库连接配置项。 的本地化字符串。
        /// </summary>
        public static string NotExistsDatabaseConfig {
            get {
                return ResourceManager.GetString("NotExistsDatabaseConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前应用程序配置文件中不存在数据库提供程序为 &quot;{0}&quot; 数据库连接配置项。 的本地化字符串。
        /// </summary>
        public static string NotExistsSpecifiedProviderDatabaseConfig {
            get {
                return ResourceManager.GetString("NotExistsSpecifiedProviderDatabaseConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的参数 providerName: &quot;{0}&quot; 值无效，该数据库提供程序未注册。 的本地化字符串。
        /// </summary>
        public static string UnregisteredProviderName {
            get {
                return ResourceManager.GetString("UnregisteredProviderName", resourceCulture);
            }
        }
    }
}
