//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDF {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDF.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 传入的数组参数 &quot;{0}&quot; 中至少应存在一个元素的值不为 Null。 的本地化字符串。
        /// </summary>
        public static string Check_AnyNotNull {
            get {
                return ResourceManager.GetString("Check_AnyNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的数组参数 &quot;{0}&quot; 中存在有某个元素所示的类型不是参数数组 &quot;{1}&quot; 中任意一个元素所示的类型或接口的子类或实现。 的本地化字符串。
        /// </summary>
        public static string Check_ArrayIsRangeTypes {
            get {
                return ResourceManager.GetString("Check_ArrayIsRangeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的数组参数 &quot;{0}&quot; 值不能为 null 、空数组或空集合。 的本地化字符串。
        /// </summary>
        public static string Check_ArrayNotEmpty {
            get {
                return ResourceManager.GetString("Check_ArrayNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的参数 a:&quot;{0}&quot; 所表示的类型不可以从传入的另一参数 b:&quot;{1}&quot; 所表示的类型的实例分配。 的本地化字符串。
        /// </summary>
        public static string Check_AssignableFrom {
            get {
                return ResourceManager.GetString("Check_AssignableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的参数 &quot;{0}&quot; 的值只能为 Null、空字符串或者值 &quot;{1}&quot;。 的本地化字符串。
        /// </summary>
        public static string Check_EmptyOrEquals {
            get {
                return ResourceManager.GetString("Check_EmptyOrEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的参数 &quot;{0}&quot; 的值只能为 &quot;{1}&quot;。 的本地化字符串。
        /// </summary>
        public static string Check_Equals {
            get {
                return ResourceManager.GetString("Check_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的参数 a:&quot;{0}&quot; 所表示的类型不是继承或等价于传入的另一参数 b:&quot;{1}&quot; 所表示的类型。 的本地化字符串。
        /// </summary>
        public static string Check_InhertOf {
            get {
                return ResourceManager.GetString("Check_InhertOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的参数 &quot;{0}&quot; 所示的类型不是一个 .NET 类型定义（即，不是值类型或者接口）。 的本地化字符串。
        /// </summary>
        public static string Check_IsClass {
            get {
                return ResourceManager.GetString("Check_IsClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的参数 &quot;{0}&quot; 值不能其所代表的类型的默认值(class 类型为 null，struct 类型为初始化为零或 null 的每个结构成员)。 的本地化字符串。
        /// </summary>
        public static string Check_IsDefault {
            get {
                return ResourceManager.GetString("Check_IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的参数 &quot;{0}&quot; 所示的类型不是一个接口类型（即，不是类或值类型）。 的本地化字符串。
        /// </summary>
        public static string Check_IsInterface {
            get {
                return ResourceManager.GetString("Check_IsInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的参数 &quot;{0}&quot; 所示的类型不是参数数组 &quot;{1}&quot; 中任意一个元素所示的类型或接口的子类或实现。 的本地化字符串。
        /// </summary>
        public static string Check_IsRangeTypes {
            get {
                return ResourceManager.GetString("Check_IsRangeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的参数 &quot;{0}&quot; 所示的类型不是一个值类型。 的本地化字符串。
        /// </summary>
        public static string Check_IsValueType {
            get {
                return ResourceManager.GetString("Check_IsValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的参数 &quot;{0}&quot; 值不能为 null、空或者空白字符串。 的本地化字符串。
        /// </summary>
        public static string Check_NotEmpty {
            get {
                return ResourceManager.GetString("Check_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的参数 a:&quot;{0}&quot; 所表示的类型不是从传入的另一参数 b:&quot;{1}&quot; 所表示的类型派生的。 的本地化字符串。
        /// </summary>
        public static string Check_SubclassOf {
            get {
                return ResourceManager.GetString("Check_SubclassOf", resourceCulture);
            }
        }
    }
}
